### ISSUE TITLE
Refresh token expired - 500 Error

### ISSUE THREAD

**Issue by imneonizer** [imneonizer/autolycus#57]
````bash
203.192.236.190 - - [06/Feb/2022:06:41:09 +0000] "GET /api/auth/user-details HTTP/1.1" 500 37 "http://autolycus.duckdns.org/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36"
203.192.236.190 - - [06/Feb/2022:06:41:09 +0000] "OPTIONS /api/auth/refresh-token HTTP/1.1" 200 0 "http://autolycus.duckdns.org/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36"
2022-02-06 06:41:09 [21] [ERROR] Exception on /api/auth/refresh-token [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask_jwt_extended/view_decorators.py", line 159, in wrapper
    verify_jwt_refresh_token_in_request()
  File "/usr/local/lib/python3.7/site-packages/flask_jwt_extended/view_decorators.py", line 89, in verify_jwt_refresh_token_in_request
    jwt_data, jwt_header = _decode_jwt_from_request(request_type='refresh')
  File "/usr/local/lib/python3.7/site-packages/flask_jwt_extended/view_decorators.py", line 294, in _decode_jwt_from_request
    decoded_token = decode_token(encoded_token, csrf_token)
  File "/usr/local/lib/python3.7/site-packages/flask_jwt_extended/utils.py", line 118, in decode_token
    allow_expired=allow_expired
  File "/usr/local/lib/python3.7/site-packages/flask_jwt_extended/tokens.py", line 143, in decode_jwt
    leeway=leeway, options=options, issuer=issuer)
  File "/usr/local/lib/python3.7/site-packages/jwt/api_jwt.py", line 104, in decode
    self._validate_claims(payload, merged_options, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jwt/api_jwt.py", line 134, in _validate_claims
    self._validate_exp(payload, now, leeway)
  File "/usr/local/lib/python3.7/site-packages/jwt/api_jwt.py", line 175, in _validate_exp
    raise ExpiredSignatureError('Signature has expired')
jwt.exceptions.ExpiredSignatureError: Signature has expired
203.192.236.190 - - [06/Feb/2022:06:41:09 +0000] "POST /api/auth/refresh-token HTTP/1.1" 500 37 "http://autolycus.duckdns.org/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36"
````

**Comment by imneonizer** [comment]
fixed in #65
